object ColumnNames {
  val NestedObjectSchema = "array<struct<id:INT, name:STRING>>"
  val BudgetCol = "budget"
  val RevenueCol = "revenue"
  val PopularityCol = "popularity"
  val ProductionCompaniesCol = "production_companies"
  val IdCol = "id"
  val TitleCol = "title"
  val ProfitCol = "profit"
  val GenresCol = "genres"
  val ReleaseDateCol = "release_date"
  val ReleaseYrCol = "releaseYear"
  val CompanyIdCol = "companyId"
  val MovieIdCol = "movieId"
  val GenreIdCol = "genreId"
  val Genre = "genre"
  val Company = "company"
  val NameCol = "name"
}
